using NexYaml.Parser;
using NexYaml.Serialization;
using NexYaml;
using Stride.Core;
using System;

// <auto-generated/>
//  This code was generated by Strides YamlSerializer.
//  Do not edit this file.

#nullable enable

namespace NexYaml;
[System.CodeDom.Compiler.GeneratedCode("NexVYaml", "1.0.0.0")]
public struct VectorFactory : IYamlSerializerFactory
{

    public void Register(IYamlSerializerResolver resolver)
    {
        resolver.Register(this, typeof(Stride.Core.Mathematics.Vector3), typeof(Stride.Core.Mathematics.Vector3));
        resolver.RegisterTag($"Stride.Core.Mathematics.Vector3,Terrain1", typeof(Stride.Core.Mathematics.Vector3));
        var serializer = new NexSourceGenerated_Terrain1_YamlExtensionsVector3();
        resolver.RegisterSerializer(serializer);

        resolver.Register(this, typeof(Stride.Core.Mathematics.Vector3), typeof(System.ValueType));


    }
    public YamlSerializer Instantiate(Type type)
    {
        if (type == typeof(System.ValueType)) { return new NexSourceGenerated_Terrain1_YamlExtensionsVector3(); }

        return new NexSourceGenerated_Terrain1_YamlExtensionsVector3();
    }
}
file sealed class ExternWrapper
{

}
[System.CodeDom.Compiler.GeneratedCode("NexVYaml", "1.0.0.0")]
file sealed class NexSourceGenerated_Terrain1_YamlExtensionsVector3 : YamlSerializer<Stride.Core.Mathematics.Vector3>
{

    private static readonly byte[] UTF8X = new byte[] { 88 };
    private static readonly byte[] UTF8Y = new byte[] { 89 };
    private static readonly byte[] UTF8Z = new byte[] { 90 };
    protected override DataStyle Style { get; } = DataStyle.Compact;

    public override void Write(IYamlWriter stream, Stride.Core.Mathematics.Vector3 value, DataStyle style = DataStyle.Any)
    {
        stream.BeginMapping(style == DataStyle.Any ? Style : style);
        stream.WriteTag("!Stride.Core.Mathematics.Vector3,Terrain1");
        stream.Write("X", value.X, style);
        stream.Write("Y", value.Y, style);
        stream.Write("Z", value.Z, style);

        stream.EndMapping();
    }

    public override void Read(IYamlReader stream, ref Stride.Core.Mathematics.Vector3 value, ref ParseResult parseResult)
    {
        var __TEMP__X = default(float);
        ParseResult __TEMP__RESULT__X = new();
        var __TEMP__Y = default(float);
        ParseResult __TEMP__RESULT__Y = new();
        var __TEMP__Z = default(float);
        ParseResult __TEMP__RESULT__Z = new();

        stream.ReadMapping((key) => {
            if (
                !stream.TryRead(ref __TEMP__X, ref key, UTF8X, ref __TEMP__RESULT__X) &&
                !stream.TryRead(ref __TEMP__Y, ref key, UTF8Y, ref __TEMP__RESULT__Y) &&
                !stream.TryRead(ref __TEMP__Z, ref key, UTF8Z, ref __TEMP__RESULT__Z)
            )
            {
                stream.SkipRead();
            }


        });

        var __TEMP__RESULT = new Stride.Core.Mathematics.Vector3
        {
            X = __TEMP__X,
            Y = __TEMP__Y,
            Z = __TEMP__Z
        };

        value = __TEMP__RESULT;
    }
}
